# Generated by Django 3.1.7 on 2021-04-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_groups', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='group',
            field=models.ManyToManyField(blank=True, to='study_groups.StudyGroup'),
        ),
    ]
