stages:
  - build
  - deploy

services:
  - docker:dind

image: docker:stable

variables:
  DOCKER_DRIVER: overlay
  HEROKU_APP_NAME: labs-management
  HEROKU_REGISTRY_IMAGE: registry.heroku.com/${HEROKU_APP_NAME}/web
  IMAGE: ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}

build:
  stage: build
  script:
    - cd app
    - echo "Start building App"
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $IMAGE:latest || true
    - docker build
      --cache-from $IMAGE:latest
      --tag $IMAGE:latest
      --file ./Dockerfile.prod
      "."
    - docker push $IMAGE:latest
    - echo "Build successfully!"
  artifacts:
    expire_in: 1 hour

deploy:
  stage: deploy
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    HEROKU_APP_NAME: labs-management
    HEROKU_REGISTRY_IMAGE: registry.heroku.com/${HEROKU_APP_NAME}/web
  script:
    - apk add --no-cache curl
    - cd app
    - docker build
        --tag $HEROKU_REGISTRY_IMAGE
        --file ./Dockerfile.prod
        "."
    - docker login -u _ -p $HEROKU_AUTH_TOKEN registry.heroku.com
    - docker push $HEROKU_REGISTRY_IMAGE
    - cd ..
    - chmod +x ./release.sh
    - ./release.sh