# Generated by Django 3.1.7 on 2021-04-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
        ('users', '0002_auto_20210402_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructorprofile',
            name='subject',
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='subject',
            field=models.ManyToManyField(blank=True, to='subjects.Subject'),
        ),
    ]
